(define (problem generalkehck)
(:domain bge)
(:objects secundo governor reaper sarco imperator albinorat squarekey highpriest lagoon slaughterhouse armadillo jade pearl1 pterolimax factory doubleh peyjmdisk pearl2 lagoon2 mammago city mingtzu akuda seagull pearl5 gyrodisk conspiracy pedestrian starkos lighthouse blackisle issam greenspider selene you peyj daijo2 kbups generalkehck pearl3 pod pearl4 vorax treasureloc spiriteater aurorawhale circlekey mingtzushop hahn daijo )
(:init (adjacent mammago lagoon)
(character highpriest)
(has you daijo2)
(bad generalkehck)
(has mingtzu starkos)
(at vorax slaughterhouse)
(at highpriest selene)
(character hahn)
(animal vorax)
(adjacent lagoon2 blackisle)
(item circlekey)
(adjacent pedestrian mingtzushop)
(at spiriteater slaughterhouse)
(at pterolimax blackisle)
(bad highpriest)
(at generalkehck city)
(animal seagull)
(character secundo)
(friend jade peyj)
(monster imperator)
(item pearl4)
(at secundo lighthouse)
(information treasureloc)
(friend jade secundo)
(location blackisle)
(at seagull lagoon)
(adjacent lagoon2 slaughterhouse)
(at reaper factory)
(item pod)
(at imperator lagoon)
(captive reaper doubleh)
(at doubleh factory)
(adjacent lagoon city)
(location pedestrian)
(at you lighthouse)
(location factory)
(has reaper gyrodisk)
(character governor)
(character jade)
(animal greenspider)
(at peyj lighthouse)
(adjacent lagoon2 factory)
(weapon daijo)
(at aurorawhale lagoon2)
(item pearl1)
(has pterolimax pearl1)
(location city)
(has mingtzu pearl5)
(= (total-cost) 0)
(location slaughterhouse)
(adjacent city pedestrian)
(adjacent city lagoon2)
(has imperator pearl3)
(item peyjmdisk)
(item kbups)
(at sarco blackisle)
(item starkos)
(location lagoon2)
(monster reaper)
(player you)
(location mingtzushop)
(has spiriteater pearl4)
(has issam pod)
(adjacent pedestrian akuda)
(item pearl5)
(at mingtzu mingtzushop)
(at greenspider factory)
(location lagoon)
(character issam)
(animal albinorat)
(animal aurorawhale)
(at jade lighthouse)
(weapon daijo2)
(location lighthouse)
(item pearl3)
(item squarekey)
(at armadillo lighthouse)
(adjacent lagoon selene)
(character doubleh)
(weapon gyrodisk)
(has reaper pearl2)
(adjacent lighthouse lagoon)
(has spiriteater treasureloc)
(character peyj)
(location mammago)
(monster pterolimax)
(has peyj peyjmdisk)
(character generalkehck)
(monster sarco)
(animal armadillo)
(has mingtzu kbups)
(location selene)
(friend hahn doubleh)
(item pearl2)
(at albinorat pedestrian)
(has jade daijo)
(has doubleh conspiracy)
(at hahn akuda)
(at governor city)
(location akuda)
(monster spiriteater)
(information conspiracy)
(at issam mammago)
(character mingtzu)
)
(:goal  (defended jade))
(:metric minimize (total-cost)))