(define (problem generalkehck)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod pearl1 kbups circlekey starkos pearl2 pearl5 pearl4 pearl3 squarekey - artifact
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (adjacent pedestrian mingtzushop)
(adjacent mammago lagoon)
(at hahn akuda)
(at jade lighthouse)
(at governor city)
(adjacent lagoon2 slaughterhouse)
(at highpriest selene)
(adjacent lagoon2 factory)
(at aurorawhale lagoon2)
(adjacent city pedestrian)
(friend jade secundo)
(at mingtzu mingtzushop)
(adjacent lighthouse lagoon)
(at secundo lighthouse)
(at spiriteater slaughterhouse)
(has reaper pearl2)
(at you lighthouse)
(at issam mammago)
(has issam pod)
(= (total-cost) 0)
(at albinorat pedestrian)
(adjacent lagoon selene)
(has jade daijo)
(adjacent lagoon2 blackisle)
(has peyj peyjmdisk)
(at generalkehck city)
(has spiriteater treasureloc)
(at pterolimax blackisle)
(at reaper factory)
(at doubleh factory)
(at greenspider factory)
(has doubleh conspiracy)
(has mingtzu starkos)
(has mingtzu kbups)
(has you daijo2)
(captive reaper doubleh)
(has pterolimax pearl1)
(at vorax slaughterhouse)
(has imperator pearl3)
(friend hahn doubleh)
(adjacent city lagoon2)
(adjacent lagoon city)
(friend jade peyj)
(has spiriteater pearl4)
(at peyj lighthouse)
(at sarco blackisle)
(adjacent pedestrian akuda)
(has reaper gyrodisk)
(has mingtzu pearl5)
(at imperator lagoon)
(at seagull lagoon)
(at armadillo lighthouse)
(has doubleh circlekey)
)
(:goal (and (defended highpriest) (defended mingtzu) (has peyj kbups)))
(:metric minimize (total-cost)))