(define (problem generalkehck)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod kbups circlekey starkos squarekey - artifact
  pearl2 pearl5 pearl4 pearl3 pearl1 - pearl
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (at imperator lagoon)
(adjacent lighthouse lagoon)
(at pterolimax blackisle)
(friend hahn doubleh)
(adjacent lagoon selene)
(adjacent city lagoon2)
(at mingtzu mingtzushop)
(adjacent lagoon2 blackisle)
(at greenspider factory)
(at generalkehck city)
(at you lighthouse)
(adjacent pedestrian akuda)
(at albinorat pedestrian)
(has imperator pearl3)
(adjacent lagoon city)
(at aurorawhale lagoon2)
(friend jade secundo)
(has jade daijo)
(has you daijo2)
(at issam mammago)
(has mingtzu pearl5)
(at highpriest selene)
(adjacent mammago lagoon)
(= (total-cost) 0)
(at spiriteater slaughterhouse)
(at sarco blackisle)
(has spiriteater treasureloc)
(at doubleh factory)
(has reaper gyrodisk)
(has peyj peyjmdisk)
(adjacent pedestrian mingtzushop)
(has mingtzu kbups)
(has issam pod)
(adjacent city pedestrian)
(at armadillo lighthouse)
(at vorax slaughterhouse)
(friend jade peyj)
(at reaper factory)
(adjacent lagoon2 factory)
(has mingtzu starkos)
(captive reaper doubleh)
(at hahn akuda)
(has spiriteater pearl4)
(adjacent lagoon2 slaughterhouse)
(at peyj lighthouse)
(has doubleh conspiracy)
(has doubleh circlekey)
(at governor city)
(at jade lighthouse)
(at secundo lighthouse)
(at seagull lagoon)
(has reaper pearl2)
(has pterolimax pearl1)
)
(:goal  (captive you secundo))
(:metric minimize (total-cost)))