(define (problem peyj)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod pearl1 kbups circlekey starkos pearl2 pearl5 pearl4 pearl3 squarekey - artifact
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (adjacent lighthouse lagoon)
(at generalkehck city)
(adjacent city pedestrian)
(at imperator lagoon)
(at greenspider factory)
(adjacent mammago lagoon)
(adjacent city lagoon2)
(has mingtzu starkos)
(at doubleh factory)
(at aurorawhale lagoon2)
(has reaper pearl2)
(has spiriteater pearl4)
(at reaper factory)
(has peyj peyjmdisk)
(at pterolimax blackisle)
(= (total-cost) 0)
(at governor city)
(at armadillo lighthouse)
(has issam pod)
(friend jade secundo)
(at albinorat pedestrian)
(adjacent lagoon2 factory)
(at issam mammago)
(at secundo lighthouse)
(has imperator pearl3)
(captive reaper doubleh)
(has spiriteater treasureloc)
(adjacent lagoon selene)
(at peyj lighthouse)
(adjacent pedestrian akuda)
(adjacent pedestrian mingtzushop)
(at highpriest selene)
(has doubleh conspiracy)
(at spiriteater slaughterhouse)
(friend jade peyj)
(adjacent lagoon city)
(adjacent lagoon2 blackisle)
(has jade daijo)
(at seagull lagoon)
(has pterolimax pearl1)
(has reaper gyrodisk)
(at sarco blackisle)
(at vorax slaughterhouse)
(has you daijo2)
(at hahn akuda)
(at jade lighthouse)
(adjacent lagoon2 slaughterhouse)
(at mingtzu mingtzushop)
(has mingtzu pearl5)
(at you lighthouse)
(friend hahn doubleh)
(has mingtzu kbups)
)
(:goal (and (defended kbups) (used starkos) (at jade slaughterhouse)))
(:metric minimize (total-cost)))