(define (problem peyj)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod pearl1 kbups circlekey starkos pearl2 pearl5 pearl4 pearl3 squarekey - artifact
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (at you lighthouse)
(at greenspider factory)
(adjacent lagoon2 blackisle)
(adjacent lagoon2 factory)
(adjacent pedestrian akuda)
(at albinorat pedestrian)
(friend hahn doubleh)
(has jade daijo)
(friend jade peyj)
(has spiriteater pearl4)
(at secundo lighthouse)
(at armadillo lighthouse)
(at hahn akuda)
(adjacent lagoon2 slaughterhouse)
(has mingtzu pearl5)
(has spiriteater treasureloc)
(friend jade secundo)
(at aurorawhale lagoon2)
(at vorax slaughterhouse)
(at imperator lagoon)
(at doubleh factory)
(has pterolimax pearl1)
(at seagull lagoon)
(has doubleh conspiracy)
(captive reaper doubleh)
(has imperator pearl3)
(has doubleh circlekey)
(adjacent city pedestrian)
(has reaper pearl2)
(adjacent pedestrian mingtzushop)
(at issam mammago)
(has mingtzu starkos)
(adjacent lighthouse lagoon)
(adjacent city lagoon2)
(has reaper gyrodisk)
(adjacent lagoon selene)
(at reaper factory)
(at pterolimax blackisle)
(at spiriteater slaughterhouse)
(has you daijo2)
(adjacent mammago lagoon)
(at peyj lighthouse)
(has issam pod)
(at sarco blackisle)
(adjacent lagoon city)
(has mingtzu kbups)
(at generalkehck city)
(at mingtzu mingtzushop)
(at highpriest selene)
(at governor city)
(= (total-cost) 0)
(has peyj peyjmdisk)
(at jade lighthouse)
)
(:goal (and (explored pedestrian) (used peyjmdisk) (has jade circlekey)))
(:metric minimize (total-cost)))