(define (problem jade)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod pearl1 kbups circlekey starkos pearl2 pearl5 pearl4 pearl3 squarekey - artifact
  daijo daijo2 gyrodisk
  treasureloc conspiracy - information)
(:init (at issam mammago)
(at spiriteater slaughterhouse)
(at sarco blackisle)
(at albinorat pedestrian)
(at vorax slaughterhouse)
(has imperator pearl3)
(friend jade peyj)
(adjacent pedestrian akuda)
(has spiriteater pearl4)
(at reaper factory)
(captive reaper doubleh)
(at pterolimax blackisle)
(has mingtzu pearl5)
(adjacent lagoon selene)
(at greenspider factory)
(at armadillo lighthouse)
(at aurorawhale lagoon2)
(adjacent lagoon city)
(has you daijo2)
(has mingtzu kbups)
(adjacent city lagoon2)
(adjacent city pedestrian)
(has doubleh conspiracy)
(has mingtzu starkos)
(adjacent pedestrian mingtzushop)
(has reaper pearl2)
(at secundo lighthouse)
(at you lighthouse)
(adjacent lagoon2 slaughterhouse)
(at generalkehck city)
(has pterolimax pearl1)
(at governor city)
(at jade lighthouse)
(adjacent lagoon2 factory)
(adjacent lighthouse lagoon)
(has spiriteater treasureloc)
(at mingtzu mingtzushop)
(friend jade secundo)
(= (total-cost) 0)
(at highpriest selene)
(adjacent lagoon2 blackisle)
(has issam pod)
(has peyj peyjmdisk)
(at doubleh factory)
(adjacent mammago lagoon)
(has jade daijo)
(at hahn akuda)
(friend hahn doubleh)
(has reaper gyrodisk)
(at seagull lagoon)
(at imperator lagoon)
(at peyj lighthouse)
)
(:goal  (has peyj conspiracy))
(:metric minimize (total-cost)))
