(define (problem jade)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod kbups circlekey starkos squarekey - artifact
  pearl2 pearl5 pearl4 pearl3 pearl1 - pearl
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (adjacent lagoon city)
(at albinorat pedestrian)
(has peyj peyjmdisk)
(has spiriteater treasureloc)
(has mingtzu starkos)
(has reaper gyrodisk)
(adjacent lighthouse lagoon)
(has pterolimax pearl1)
(= (total-cost) 0)
(at you lighthouse)
(adjacent lagoon2 blackisle)
(adjacent pedestrian akuda)
(friend jade peyj)
(has mingtzu kbups)
(at pterolimax blackisle)
(has doubleh circlekey)
(at reaper factory)
(friend hahn doubleh)
(has reaper pearl2)
(adjacent city lagoon2)
(at seagull lagoon)
(at vorax slaughterhouse)
(has you daijo2)
(at governor city)
(friend jade secundo)
(has mingtzu pearl5)
(adjacent mammago lagoon)
(at mingtzu mingtzushop)
(at jade lighthouse)
(has doubleh conspiracy)
(adjacent pedestrian mingtzushop)
(at sarco blackisle)
(adjacent lagoon2 factory)
(captive reaper doubleh)
(at armadillo lighthouse)
(at imperator lagoon)
(at doubleh factory)
(has imperator pearl3)
(at hahn akuda)
(at aurorawhale lagoon2)
(at issam mammago)
(adjacent city pedestrian)
(adjacent lagoon selene)
(at generalkehck city)
(at peyj lighthouse)
(at highpriest selene)
(has spiriteater pearl4)
(has issam pod)
(at spiriteater slaughterhouse)
(at greenspider factory)
(has jade daijo)
(adjacent lagoon2 slaughterhouse)
(at secundo lighthouse)
)
(:goal  (captive you doubleh))
(:metric minimize (total-cost)))