(define (problem jade)
(:domain bge)
(:objects highpriest peyj governor hahn mingtzu issam doubleh jade generalkehck secundo - character
  you - player
  spiriteater pterolimax sarco imperator reaper - monster
  aurorawhale greenspider seagull albinorat armadillo vorax - animal
  selene lagoon lagoon2 mammago slaughterhouse lighthouse city pedestrian factory akuda mingtzushop blackisle - location
  peyjmdisk pod pearl1 kbups circlekey starkos pearl2 pearl5 pearl4 pearl3 squarekey - artifact
  daijo daijo2 gyrodisk - weapon
  treasureloc conspiracy - information)
(:init (at spiriteater slaughterhouse)
(at greenspider factory)
(has reaper gyrodisk)
(has peyj peyjmdisk)
(at pterolimax blackisle)
(friend jade secundo)
(has spiriteater pearl4)
(has pterolimax pearl1)
(adjacent lagoon2 factory)
(adjacent city lagoon2)
(adjacent pedestrian akuda)
(at doubleh factory)
(at highpriest selene)
(at generalkehck city)
(has you daijo2)
(at issam mammago)
(at imperator lagoon)
(adjacent lighthouse lagoon)
(has imperator pearl3)
(has issam pod)
(= (total-cost) 0)
(has mingtzu starkos)
(has mingtzu pearl5)
(friend jade peyj)
(adjacent lagoon2 slaughterhouse)
(at vorax slaughterhouse)
(at you lighthouse)
(at mingtzu mingtzushop)
(adjacent city pedestrian)
(at sarco blackisle)
(at aurorawhale lagoon2)
(at armadillo lighthouse)
(adjacent mammago lagoon)
(adjacent lagoon city)
(has reaper pearl2)
(adjacent lagoon2 blackisle)
(at secundo lighthouse)
(adjacent pedestrian mingtzushop)
(at seagull lagoon)
(has jade daijo)
(adjacent lagoon selene)
(has doubleh conspiracy)
(has spiriteater treasureloc)
(at reaper factory)
(at governor city)
(at albinorat pedestrian)
(at jade lighthouse)
(friend hahn doubleh)
(at hahn akuda)
(has mingtzu kbups)
(at peyj lighthouse)
(captive reaper doubleh)
)
(:goal (and (defended mingtzu) (captive you governor)))
(:metric minimize (total-cost)))