echo ""
echo "CHARACTER : jade"
echo "AIM : (has governor conspiracy)"
echo " "
echo "move you lighthouse lagoon"
echo "move you lagoon city"
echo "move you city lagoon2"
echo "kill you imperator lagoon2 daijo2"
echo "move you lagoon2 factory"
echo "stealth you"
echo "kill you reaper factory daijo2"
echo "listen you doubleh factory conspiracy"
echo "move you factory lagoon2"
echo "move you lagoon2 city"
echo "report you governor conspiracy city"
echo ""
echo "Plan Cost : 15"
echo ""
echo "1"
echo "1"
echo "1"
echo "2"
echo "1"
echo "1"
echo "2"
echo "2"
echo "1"
echo "1"
echo "2"
echo ""
